# Generated by Django 5.0.3 on 2024-03-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0002_customuser_address_customuser_avatar_customuser_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
