# Generated by Django 5.0.3 on 2024-03-06 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userfollowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
